FROM openjdk:11
ADD target/PensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar PensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 9002
ENTRYPOINT ["java", "-jar" , "PensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar"]